name: google_maps_custom_tooltip
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.4 <=3.0.0'
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.3
  google_maps_flutter_web: ^0.4.0+5
  pointer_interceptor: ^0.9.3+3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
